### ISSUE TITLE
`document` not defined on server-side rendering

### ISSUE THREAD

**Issue by karissa** [patrick-steele-idem/morphdom#95]
After 2.3.0, getting 'document' not defined when using browserify with `yo-yo` for server side rendering. 

```
Unhandled rejection ReferenceError: document is not defined
    at Object.<anonymous> (/Users/karissa/node_modules/dat.land/node_modules/morphdom/dist/morphdom.js:6:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/karissa/node_modules/dat.land/node_modules/yo-yo/index.js:2:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

cc @shama @maxogden @yoshuawuyts

**Comment by karissa** [comment]
thanks @patrick-steele-idem !
